### ISSUE TITLE
Which licence is this released under?

### ISSUE THREAD

**Issue by robinpaulson** [nicoguaro/material_database#2]
Might I suggest ODBL?
https://en.wikipedia.org/wiki/ODbL

The concept behind the project is excellent, it would be great to see it expand. Perhaps a free licence will assist with that?

**Comment by nicoguaro** [comment]
@robinpaulson, I forgot about adding a license.

I think I would prefer to use [ODC-BY 1.0 license](https://opendatacommons.org/licenses/by/summary/). I don't like the viral-like licenses with the share-alike clause. What do you think? This would be my first _data_ license.

Thanks for the interest and to point out the lack of license.

    https://opendatacommons.org/licenses/by/

since

**Comment by nicoguaro** [comment]
Closed by 3d58ef456fd0e9185c886b212de3247c68e05793.
